### ISSUE TITLE
Support auto-save

### ISSUE THREAD

**Issue by jmuk** [karino2/editbook#10]
Save buttons are so 1990's. Software needs to take care of such thing.

**Comment by karino2** [comment]
Agree.
Curretly, save is  implemented  by  sending whole contents via post requset.
If we want to support auto save, we should only send diff via  websocket.

I think this change is not so difficult and we should do it in some future.

**Comment by karino2** [comment]
I've used this app for a while, and feel current save operation is not so bad.
I close this issue for a while and open later if needed.
