### ISSUE TITLE
make setup more friendly with go-get

### ISSUE THREAD

**Issue by jmuk** [karino2/editbook#14]
Currently the code assumes data (`static/` and `editors/`) will be in the same directory where the binary exists (https://github.com/karino2/editbook/blob/master/main.go#L170). This will not be the case when the user installs the package through `go get` command -- the source code (and data directories) will be in `$GOPATH/src/github.com/karino2/editbook` while the binary will be installed to `$GOPATH/bin`.

Here are some ideas:
1. Use https://andrewbrookins.com/tech/golang-get-directory-of-the-current-file/ this technique to find out where originally the main.go exists.
2. Check out `$GOPATH` environment variable -- and look for the path by itself.
3. Embed those static files into the binary.
4. Allow specifying the root directory through the command-line option

**Comment by karino2** [comment]
Taking into account of current development stage, I don't like option 3 for a while (though I also think this is the best option in the future).

I couldn't understand option 1.

I feel option 2 is enough for a while.

**Comment by jmuk** [comment]
Option 1 is to use `runtime.Caller`, which returns the location of the source code. This is primarily for debugging use, so the source location means the location when the file is compiled.

However that would work and be good enough considering `go get` or `go run` or manual source compilations. This will not work in many other cases, like binary-only distribution.

**Comment by jmuk** [comment]
Also, it would be nicer to print out warning messages when the `static/` and/or `editors/` directories do not exist when starting the server.

**Comment by karino2** [comment]
Either 1 or 2  is OK for  me.

**Comment by karino2** [comment]
Adopt option 1.
