### ISSUE TITLE
Introduce ESLint on CI

### ISSUE THREAD

**Issue by tetsuharuohzeki** [karino2/editbook#17]
## Abstract

- [ESLint](http://eslint.org/) is a de-facto lint tool in today's JavaScript (ECMAScript) world. This lint tool is built on some static analytic libraries. Its features covers not only coding styles also an error detection.
- It has a auto-fix mode to fix style (run with `--fix` command line flag).
- And some editor has a integration for it (e.g. [vscode-eslint](https://github.com/Microsoft/vscode-eslint)).

## Dependencies

- Enable CI (TravisCI or others)
- Choose rules which we enables. ESLint's rules are opt-in at all. But there are some presets.
  - All rules has 3 level, "disabled", "enabled (warn), and "enabled (error)".
  - `eslint:recommended` is built-in rule set.
  - [`eslint-config-airbnb`](https://www.npmjs.com/package/eslint-config-airbnb) is well known rule set.

**Comment by tetsuharuohzeki** [comment]
> Choose rules

Some project has specific rules in their tree. It is reasonable choice to copy it to this tree.

**Comment by karino2** [comment]
Related PR. #23

**Comment by tetsuharuohzeki** [comment]
I think this should be closed because https://github.com/karino2/editbook/issues/26 has been landed.

ESLint is still failed on CI. It should be handled by https://github.com/karino2/editbook/issues/27
