### ISSUE TITLE
Pass ESLint for editors/monaco/

### ISSUE THREAD

**Issue by tetsuharuohzeki** [karino2/editbook#27]

**Comment by tetsuharuohzeki** [comment]
At this time, `editors/monaco/` is failed on ESLint test. This is meaningless situation even if we introduce it and enable CI on this repository.

**Comment by karino2** [comment]
See also: https://travis-ci.org/karino2/editbook

**Comment by karino2** [comment]
Is this already fixed in #32 PR?

**Comment by tetsuharuohzeki** [comment]
I agree this has been fixed in #32
