### ISSUE TITLE
language server does not work on windows environment.

### ISSUE THREAD

**Issue by karino2** [karino2/editbook#33]
TODO: investigate this.
Seems path separator problem.

**Comment by karino2** [comment]
For go language server, official document says go lang server is not supported on windows environment.
So I check tsserver instead.

When open js file, developer console log says:
Error: Could not find file: 'file://d%3A%5Cgo%5Csrc%5Cgithub.com%5Ckarino2%5Ceditbook%5Ceditors%5Cmonaco%5Ceditbook_main.js'. at i (http://localhost:5123/editor/vs/language/typescript/lib/typescriptServices.js:58:30724) at Object.l [as getSyntacticDiagnostics] (http://localhost:5123/editor/vs/language/typescript/lib/typescriptServices.js:59:1460) at e.getSyntacticDiagnostics (http://localhost:5123/editor/vs/language/typescript/src/worker.js:9:1738) at t.e.fmr (http://localhost:5123/editor/vs/base/worker/workerMain.js:11:8485) at t._handleMessage (http://localhost:5123/editor/vs/base/worker/workerMain.js:10:5976) at Object.handleMessage (http://localhost:5123/editor/vs/base/worker/workerMain.js:10:5593) at e._handleMessage (http://localhost:5123/editor/vs/base/worker/workerMain.js:10:3668) at e.handleMessage (http://localhost:5123/editor/vs/base/worker/workerMain.js:10:3238) at t.onmessage (http://localhost:5123/editor/vs/base/worker/workerMain.js:10:5672) at self.onmessage (http://localhost:5123/editor/vs/base/worker/workerMain.js:11:9792)

**Comment by karino2** [comment]
I try modifying all the model.uri.path in languageservice.js with
            model.uri.path.replace(/\\/g, "/"),
But error seems persist.
I'm wondering who create file:/// scheme?
Client side never know this is local file.

"getSyntacticDiagnostics" might be the key.

**Comment by jmuk** [comment]
This seems an error on monaco's built-in typescript mode. I believe the same error happens without tsserver / language server.

But I also think that the code like https://github.com/karino2/editbook/blob/master/editors/monaco/editbook_main.js#L219 could be problematic -- I don't remember the right format of file:// scheme for Windows paths, but the path like 'file://d%3A%5Cgo%5Csrc%5Cgithub.com%5C...' looks wrong to me.

**Comment by karino2** [comment]
Hmm, interesting.

By the way, why does this line use file scheme?
Does monaco behave differently if the url of file is file scheme?

**Comment by jmuk** [comment]
File scheme would be preferred. The primary usage is just identifier and anything could be fine if everything is within the browser, but I use this uri for the connection with the language server (like https://github.com/karino2/editbook/blob/master/editors/monaco/languageservice.js#L200). In this case, the language server processes the file specified by this uri -- in that case file scheme should be used.

**Comment by jmuk** [comment]
by the way, it seems the line in editbook_main.js seems wrong. We should use `monaco.Uri.file(path)` instead (see https://github.com/Microsoft/monaco-editor/blob/master/monaco.d.ts#L166). The implementation would take care of Windows paths (https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/uri.ts#L215)

**Comment by karino2** [comment]
It seems this issue is fixed if I use monaco.Uri.file(path).
I put many temp code now, so I clean up and try again.

**Comment by karino2** [comment]
Fixed! thanks!
